package com.hkk.ssm.pojo;

public class Clazz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.class_id
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.class_classid
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private Integer classClassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.class_classsubject
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private String classClasssubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.class_classcounsellor
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private String classClasscounsellor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.class_id
     *
     * @return the value of t_class.class_id
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.class_id
     *
     * @param classId the value for t_class.class_id
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.class_classid
     *
     * @return the value of t_class.class_classid
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public Integer getClassClassid() {
        return classClassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.class_classid
     *
     * @param classClassid the value for t_class.class_classid
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setClassClassid(Integer classClassid) {
        this.classClassid = classClassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.class_classsubject
     *
     * @return the value of t_class.class_classsubject
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public String getClassClasssubject() {
        return classClasssubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.class_classsubject
     *
     * @param classClasssubject the value for t_class.class_classsubject
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setClassClasssubject(String classClasssubject) {
        this.classClasssubject = classClasssubject == null ? null : classClasssubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.class_classcounsellor
     *
     * @return the value of t_class.class_classcounsellor
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public String getClassClasscounsellor() {
        return classClasscounsellor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.class_classcounsellor
     *
     * @param classClasscounsellor the value for t_class.class_classcounsellor
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setClassClasscounsellor(String classClasscounsellor) {
        this.classClasscounsellor = classClasscounsellor == null ? null : classClasscounsellor.trim();
    }
}