package com.hkk.ssm.pojo;

import java.util.ArrayList;
import java.util.List;

public class ClazzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public ClazzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(Integer value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(Integer value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(Integer value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(Integer value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<Integer> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<Integer> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(Integer value1, Integer value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassClassidIsNull() {
            addCriterion("class_classid is null");
            return (Criteria) this;
        }

        public Criteria andClassClassidIsNotNull() {
            addCriterion("class_classid is not null");
            return (Criteria) this;
        }

        public Criteria andClassClassidEqualTo(Integer value) {
            addCriterion("class_classid =", value, "classClassid");
            return (Criteria) this;
        }

        public Criteria andClassClassidNotEqualTo(Integer value) {
            addCriterion("class_classid <>", value, "classClassid");
            return (Criteria) this;
        }

        public Criteria andClassClassidGreaterThan(Integer value) {
            addCriterion("class_classid >", value, "classClassid");
            return (Criteria) this;
        }

        public Criteria andClassClassidGreaterThanOrEqualTo(Integer value) {
            addCriterion("class_classid >=", value, "classClassid");
            return (Criteria) this;
        }

        public Criteria andClassClassidLessThan(Integer value) {
            addCriterion("class_classid <", value, "classClassid");
            return (Criteria) this;
        }

        public Criteria andClassClassidLessThanOrEqualTo(Integer value) {
            addCriterion("class_classid <=", value, "classClassid");
            return (Criteria) this;
        }

        public Criteria andClassClassidIn(List<Integer> values) {
            addCriterion("class_classid in", values, "classClassid");
            return (Criteria) this;
        }

        public Criteria andClassClassidNotIn(List<Integer> values) {
            addCriterion("class_classid not in", values, "classClassid");
            return (Criteria) this;
        }

        public Criteria andClassClassidBetween(Integer value1, Integer value2) {
            addCriterion("class_classid between", value1, value2, "classClassid");
            return (Criteria) this;
        }

        public Criteria andClassClassidNotBetween(Integer value1, Integer value2) {
            addCriterion("class_classid not between", value1, value2, "classClassid");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectIsNull() {
            addCriterion("class_classsubject is null");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectIsNotNull() {
            addCriterion("class_classsubject is not null");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectEqualTo(String value) {
            addCriterion("class_classsubject =", value, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectNotEqualTo(String value) {
            addCriterion("class_classsubject <>", value, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectGreaterThan(String value) {
            addCriterion("class_classsubject >", value, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectGreaterThanOrEqualTo(String value) {
            addCriterion("class_classsubject >=", value, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectLessThan(String value) {
            addCriterion("class_classsubject <", value, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectLessThanOrEqualTo(String value) {
            addCriterion("class_classsubject <=", value, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectLike(String value) {
            addCriterion("class_classsubject like", value, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectNotLike(String value) {
            addCriterion("class_classsubject not like", value, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectIn(List<String> values) {
            addCriterion("class_classsubject in", values, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectNotIn(List<String> values) {
            addCriterion("class_classsubject not in", values, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectBetween(String value1, String value2) {
            addCriterion("class_classsubject between", value1, value2, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasssubjectNotBetween(String value1, String value2) {
            addCriterion("class_classsubject not between", value1, value2, "classClasssubject");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorIsNull() {
            addCriterion("class_classcounsellor is null");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorIsNotNull() {
            addCriterion("class_classcounsellor is not null");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorEqualTo(String value) {
            addCriterion("class_classcounsellor =", value, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorNotEqualTo(String value) {
            addCriterion("class_classcounsellor <>", value, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorGreaterThan(String value) {
            addCriterion("class_classcounsellor >", value, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorGreaterThanOrEqualTo(String value) {
            addCriterion("class_classcounsellor >=", value, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorLessThan(String value) {
            addCriterion("class_classcounsellor <", value, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorLessThanOrEqualTo(String value) {
            addCriterion("class_classcounsellor <=", value, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorLike(String value) {
            addCriterion("class_classcounsellor like", value, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorNotLike(String value) {
            addCriterion("class_classcounsellor not like", value, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorIn(List<String> values) {
            addCriterion("class_classcounsellor in", values, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorNotIn(List<String> values) {
            addCriterion("class_classcounsellor not in", values, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorBetween(String value1, String value2) {
            addCriterion("class_classcounsellor between", value1, value2, "classClasscounsellor");
            return (Criteria) this;
        }

        public Criteria andClassClasscounsellorNotBetween(String value1, String value2) {
            addCriterion("class_classcounsellor not between", value1, value2, "classClasscounsellor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_class
     *
     * @mbggenerated do_not_delete_during_merge Sun Feb 19 23:02:18 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_class
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}