package com.hkk.ssm.pojo;

public class Dormitory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.dormitory_id
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private Integer dormitoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.dormitory_dormitoryid
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private Integer dormitoryDormitoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.dormitory_dormitorybuilding
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private String dormitoryDormitorybuilding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.dormitory_dormitoryarea
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private String dormitoryDormitoryarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.dormitory_bedtotal
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private String dormitoryBedtotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.dormitory_livein
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private Integer dormitoryLivein;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.dormitory_leader
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    private String dormitoryLeader;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.dormitory_id
     *
     * @return the value of t_dormitory.dormitory_id
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public Integer getDormitoryId() {
        return dormitoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.dormitory_id
     *
     * @param dormitoryId the value for t_dormitory.dormitory_id
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setDormitoryId(Integer dormitoryId) {
        this.dormitoryId = dormitoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.dormitory_dormitoryid
     *
     * @return the value of t_dormitory.dormitory_dormitoryid
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public Integer getDormitoryDormitoryid() {
        return dormitoryDormitoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.dormitory_dormitoryid
     *
     * @param dormitoryDormitoryid the value for t_dormitory.dormitory_dormitoryid
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setDormitoryDormitoryid(Integer dormitoryDormitoryid) {
        this.dormitoryDormitoryid = dormitoryDormitoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.dormitory_dormitorybuilding
     *
     * @return the value of t_dormitory.dormitory_dormitorybuilding
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public String getDormitoryDormitorybuilding() {
        return dormitoryDormitorybuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.dormitory_dormitorybuilding
     *
     * @param dormitoryDormitorybuilding the value for t_dormitory.dormitory_dormitorybuilding
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setDormitoryDormitorybuilding(String dormitoryDormitorybuilding) {
        this.dormitoryDormitorybuilding = dormitoryDormitorybuilding == null ? null : dormitoryDormitorybuilding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.dormitory_dormitoryarea
     *
     * @return the value of t_dormitory.dormitory_dormitoryarea
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public String getDormitoryDormitoryarea() {
        return dormitoryDormitoryarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.dormitory_dormitoryarea
     *
     * @param dormitoryDormitoryarea the value for t_dormitory.dormitory_dormitoryarea
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setDormitoryDormitoryarea(String dormitoryDormitoryarea) {
        this.dormitoryDormitoryarea = dormitoryDormitoryarea == null ? null : dormitoryDormitoryarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.dormitory_bedtotal
     *
     * @return the value of t_dormitory.dormitory_bedtotal
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public String getDormitoryBedtotal() {
        return dormitoryBedtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.dormitory_bedtotal
     *
     * @param dormitoryBedtotal the value for t_dormitory.dormitory_bedtotal
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setDormitoryBedtotal(String dormitoryBedtotal) {
        this.dormitoryBedtotal = dormitoryBedtotal == null ? null : dormitoryBedtotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.dormitory_livein
     *
     * @return the value of t_dormitory.dormitory_livein
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public Integer getDormitoryLivein() {
        return dormitoryLivein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.dormitory_livein
     *
     * @param dormitoryLivein the value for t_dormitory.dormitory_livein
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setDormitoryLivein(Integer dormitoryLivein) {
        this.dormitoryLivein = dormitoryLivein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.dormitory_leader
     *
     * @return the value of t_dormitory.dormitory_leader
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public String getDormitoryLeader() {
        return dormitoryLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.dormitory_leader
     *
     * @param dormitoryLeader the value for t_dormitory.dormitory_leader
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setDormitoryLeader(String dormitoryLeader) {
        this.dormitoryLeader = dormitoryLeader == null ? null : dormitoryLeader.trim();
    }
}