package com.hkk.ssm.pojo;

import java.util.ArrayList;
import java.util.List;

public class StudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public StudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidIsNull() {
            addCriterion("student_studentid is null");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidIsNotNull() {
            addCriterion("student_studentid is not null");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidEqualTo(Integer value) {
            addCriterion("student_studentid =", value, "studentStudentid");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidNotEqualTo(Integer value) {
            addCriterion("student_studentid <>", value, "studentStudentid");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidGreaterThan(Integer value) {
            addCriterion("student_studentid >", value, "studentStudentid");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_studentid >=", value, "studentStudentid");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidLessThan(Integer value) {
            addCriterion("student_studentid <", value, "studentStudentid");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidLessThanOrEqualTo(Integer value) {
            addCriterion("student_studentid <=", value, "studentStudentid");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidIn(List<Integer> values) {
            addCriterion("student_studentid in", values, "studentStudentid");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidNotIn(List<Integer> values) {
            addCriterion("student_studentid not in", values, "studentStudentid");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidBetween(Integer value1, Integer value2) {
            addCriterion("student_studentid between", value1, value2, "studentStudentid");
            return (Criteria) this;
        }

        public Criteria andStudentStudentidNotBetween(Integer value1, Integer value2) {
            addCriterion("student_studentid not between", value1, value2, "studentStudentid");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentSexIsNull() {
            addCriterion("student_sex is null");
            return (Criteria) this;
        }

        public Criteria andStudentSexIsNotNull() {
            addCriterion("student_sex is not null");
            return (Criteria) this;
        }

        public Criteria andStudentSexEqualTo(String value) {
            addCriterion("student_sex =", value, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexNotEqualTo(String value) {
            addCriterion("student_sex <>", value, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexGreaterThan(String value) {
            addCriterion("student_sex >", value, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexGreaterThanOrEqualTo(String value) {
            addCriterion("student_sex >=", value, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexLessThan(String value) {
            addCriterion("student_sex <", value, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexLessThanOrEqualTo(String value) {
            addCriterion("student_sex <=", value, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexLike(String value) {
            addCriterion("student_sex like", value, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexNotLike(String value) {
            addCriterion("student_sex not like", value, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexIn(List<String> values) {
            addCriterion("student_sex in", values, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexNotIn(List<String> values) {
            addCriterion("student_sex not in", values, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexBetween(String value1, String value2) {
            addCriterion("student_sex between", value1, value2, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentSexNotBetween(String value1, String value2) {
            addCriterion("student_sex not between", value1, value2, "studentSex");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNull() {
            addCriterion("student_phone is null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNotNull() {
            addCriterion("student_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneEqualTo(Long value) {
            addCriterion("student_phone =", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotEqualTo(Long value) {
            addCriterion("student_phone <>", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThan(Long value) {
            addCriterion("student_phone >", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThanOrEqualTo(Long value) {
            addCriterion("student_phone >=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThan(Long value) {
            addCriterion("student_phone <", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThanOrEqualTo(Long value) {
            addCriterion("student_phone <=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIn(List<Long> values) {
            addCriterion("student_phone in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotIn(List<Long> values) {
            addCriterion("student_phone not in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneBetween(Long value1, Long value2) {
            addCriterion("student_phone between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotBetween(Long value1, Long value2) {
            addCriterion("student_phone not between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentClassidIsNull() {
            addCriterion("student_classid is null");
            return (Criteria) this;
        }

        public Criteria andStudentClassidIsNotNull() {
            addCriterion("student_classid is not null");
            return (Criteria) this;
        }

        public Criteria andStudentClassidEqualTo(Integer value) {
            addCriterion("student_classid =", value, "studentClassid");
            return (Criteria) this;
        }

        public Criteria andStudentClassidNotEqualTo(Integer value) {
            addCriterion("student_classid <>", value, "studentClassid");
            return (Criteria) this;
        }

        public Criteria andStudentClassidGreaterThan(Integer value) {
            addCriterion("student_classid >", value, "studentClassid");
            return (Criteria) this;
        }

        public Criteria andStudentClassidGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_classid >=", value, "studentClassid");
            return (Criteria) this;
        }

        public Criteria andStudentClassidLessThan(Integer value) {
            addCriterion("student_classid <", value, "studentClassid");
            return (Criteria) this;
        }

        public Criteria andStudentClassidLessThanOrEqualTo(Integer value) {
            addCriterion("student_classid <=", value, "studentClassid");
            return (Criteria) this;
        }

        public Criteria andStudentClassidIn(List<Integer> values) {
            addCriterion("student_classid in", values, "studentClassid");
            return (Criteria) this;
        }

        public Criteria andStudentClassidNotIn(List<Integer> values) {
            addCriterion("student_classid not in", values, "studentClassid");
            return (Criteria) this;
        }

        public Criteria andStudentClassidBetween(Integer value1, Integer value2) {
            addCriterion("student_classid between", value1, value2, "studentClassid");
            return (Criteria) this;
        }

        public Criteria andStudentClassidNotBetween(Integer value1, Integer value2) {
            addCriterion("student_classid not between", value1, value2, "studentClassid");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameIsNull() {
            addCriterion("student_classname is null");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameIsNotNull() {
            addCriterion("student_classname is not null");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameEqualTo(Integer value) {
            addCriterion("student_classname =", value, "studentClassname");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameNotEqualTo(Integer value) {
            addCriterion("student_classname <>", value, "studentClassname");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameGreaterThan(Integer value) {
            addCriterion("student_classname >", value, "studentClassname");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_classname >=", value, "studentClassname");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameLessThan(Integer value) {
            addCriterion("student_classname <", value, "studentClassname");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameLessThanOrEqualTo(Integer value) {
            addCriterion("student_classname <=", value, "studentClassname");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameIn(List<Integer> values) {
            addCriterion("student_classname in", values, "studentClassname");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameNotIn(List<Integer> values) {
            addCriterion("student_classname not in", values, "studentClassname");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameBetween(Integer value1, Integer value2) {
            addCriterion("student_classname between", value1, value2, "studentClassname");
            return (Criteria) this;
        }

        public Criteria andStudentClassnameNotBetween(Integer value1, Integer value2) {
            addCriterion("student_classname not between", value1, value2, "studentClassname");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidIsNull() {
            addCriterion("student_dormitoryid is null");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidIsNotNull() {
            addCriterion("student_dormitoryid is not null");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidEqualTo(Integer value) {
            addCriterion("student_dormitoryid =", value, "studentDormitoryid");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidNotEqualTo(Integer value) {
            addCriterion("student_dormitoryid <>", value, "studentDormitoryid");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidGreaterThan(Integer value) {
            addCriterion("student_dormitoryid >", value, "studentDormitoryid");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_dormitoryid >=", value, "studentDormitoryid");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidLessThan(Integer value) {
            addCriterion("student_dormitoryid <", value, "studentDormitoryid");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidLessThanOrEqualTo(Integer value) {
            addCriterion("student_dormitoryid <=", value, "studentDormitoryid");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidIn(List<Integer> values) {
            addCriterion("student_dormitoryid in", values, "studentDormitoryid");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidNotIn(List<Integer> values) {
            addCriterion("student_dormitoryid not in", values, "studentDormitoryid");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidBetween(Integer value1, Integer value2) {
            addCriterion("student_dormitoryid between", value1, value2, "studentDormitoryid");
            return (Criteria) this;
        }

        public Criteria andStudentDormitoryidNotBetween(Integer value1, Integer value2) {
            addCriterion("student_dormitoryid not between", value1, value2, "studentDormitoryid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_student
     *
     * @mbggenerated do_not_delete_during_merge Sun Feb 19 23:02:18 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_student
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}