package com.hkk.ssm.mapper;

import com.hkk.ssm.pojo.Dormitory;
import com.hkk.ssm.pojo.DormitoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DormitoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    int countByExample(DormitoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    int deleteByExample(DormitoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    int deleteByPrimaryKey(Integer dormitoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    int insert(Dormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    int insertSelective(Dormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    List<Dormitory> selectByExample(DormitoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    Dormitory selectByPrimaryKey(Integer dormitoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    int updateByExampleSelective(@Param("record") Dormitory record, @Param("example") DormitoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    int updateByExample(@Param("record") Dormitory record, @Param("example") DormitoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    int updateByPrimaryKeySelective(Dormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dormitory
     *
     * @mbggenerated Sun Feb 19 23:02:18 CST 2023
     */
    int updateByPrimaryKey(Dormitory record);
}